// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcB9pUVz_zp9_qASWqrA1sA78ZSNZDW_U',
    appId: '1:218810471054:web:05428f2133edb5b2462fdf',
    messagingSenderId: '218810471054',
    projectId: 'examproductive',
    authDomain: 'examproductive.firebaseapp.com',
    storageBucket: 'examproductive.appspot.com',
    measurementId: 'G-VC76052VGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgMYjiVx--V9WqwcBJpYFamOBYuxZdABI',
    appId: '1:218810471054:android:a556350583cff10c462fdf',
    messagingSenderId: '218810471054',
    projectId: 'examproductive',
    storageBucket: 'examproductive.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfv4G_JpAnjToVl7NYUfmtwWp9Lkg57ZQ',
    appId: '1:218810471054:ios:0e2ff2eab65812fc462fdf',
    messagingSenderId: '218810471054',
    projectId: 'examproductive',
    storageBucket: 'examproductive.appspot.com',
    iosBundleId: 'com.example.examProductive',
  );
}
